services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile_builder
    image: karate-connect:builder
  minimal:
    build:
      context: .
      dockerfile: Dockerfile_minimal
      args:
        - BUILDER_IMAGE=karate-connect:builder
    image: karate-connect:minimal
    depends_on:
      - builder
  python:
    build:
      context: .
      dockerfile: Dockerfile_python
      args:
        - BASE_IMAGE=karate-connect:minimal
    image: karate-connect:python
    depends_on:
      - minimal
  nominal:
    build:
      context: .
      dockerfile: Dockerfile_nominal
      args:
        - BASE_IMAGE=karate-connect:python
    image: karate-connect
    depends_on:
      - python
  aks:
    build:
      context: .
      dockerfile: Dockerfile_aks
      args:
        - BASE_IMAGE=karate-connect:python
    image: karate-connect:aks
    depends_on:
      - python
