services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile_builder
      tags:
        - karate-connect:builder
  minimal:
    build:
      context: .
      dockerfile: Dockerfile_minimal
      args:
        - BUILDER_IMAGE=karate-connect:builder
      tags:
        - karate-connect:minimal
    depends_on:
      - builder
  nominal:
    build:
      context: .
      dockerfile: Dockerfile_nominal
      args:
        - BASE_IMAGE=karate-connect:minimal
      tags:
        - karate-connect
    depends_on:
      - minimal
  aks:
    build:
      context: .
      dockerfile: Dockerfile_aks
      args:
        - BASE_IMAGE=karate-connect:minimal
      tags:
        - karate-connect:aks
    depends_on:
      - nominal
