FROM eclipse-temurin:21.0.7_6-jdk AS builder
# Install python & pip
RUN apt-get update && apt-get -y install python3 python3-pip
COPY pip.conf /root/.config/pip/pip.conf
# Install python packages
COPY requirements.txt /root/.config/pip/requirements.txt
RUN pip install -r /root/.config/pip/requirements.txt
# Run test & Build jar
COPY .git .git
COPY src src
COPY *.gradle.kts ./
COPY gradle.properties .
COPY gradlew .
COPY gradle gradle
RUN ./gradlew build
