ARG BASE_IMAGE="karate-connect:minimal"
FROM ${BASE_IMAGE} AS python
# Install pipx
RUN apt-get update && apt-get -y install pipx
# Install python packages
COPY requirements.txt /root/.config/pip/requirements.txt
RUN pipx install $(cat /root/.config/pip/requirements.txt | xargs) --include-deps
ENV PATH="/root/.local/bin:${PATH}"
