ARG BASE_IMAGE="karate-connect:minimal"
FROM ${BASE_IMAGE} AS python
# Install python & pip
RUN apt-get update && apt-get -y install python3 python3-pip
COPY pip.conf /root/.config/pip/pip.conf
# Install python packages
COPY requirements.txt /root/.config/pip/requirements.txt
RUN pip install -r /root/.config/pip/requirements.txt
