FROM eclipse-temurin:21.0.8_9-jdk AS builder
# Install pipx
RUN apt-get update && apt-get -y install pipx
# Install python packages
COPY requirements.txt /root/.config/pip/requirements.txt
RUN pipx install $(cat /root/.config/pip/requirements.txt | xargs) --include-deps
ENV PATH="/root/.local/bin:${PATH}"
# Run test & Build jar
COPY .git .git
COPY src src
COPY *.gradle.kts ./
COPY gradle.properties .
COPY gradlew .
COPY gradle gradle
RUN ./gradlew build
