ARG BASE_IMAGE="karate-connect:minimal"
FROM ${BASE_IMAGE} AS nominal
# Install python & pip
RUN apt-get update && apt-get -y install python3 python3-pip
COPY pip.conf /root/.config/pip/pip.conf
# Install python packages
COPY requirements.txt /root/.config/pip/requirements.txt
RUN pip install -r /root/.config/pip/requirements.txt
# Install kubectl
ARG KUBECTL_VERSION=1.32
RUN apt-get update && apt-get -y install apt-transport-https ca-certificates curl gnupg
RUN mkdir -p -m 755 /etc/apt/keyrings && \
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v${KUBECTL_VERSION}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
RUN chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v${KUBECTL_VERSION}/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
RUN chmod 644 /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && apt-get -y install kubectl
